site_name: AICR Documentation
site_url: https://www.mghpcc.org/
nav:
  - Home: index.md
  - AICR System: system_description.md
  - Requesting Access: request_access.md #include prerequisites
  - Getting Started: getting_started.md
  - Files and Filesystem:
    - Overview: filesystem_overview.md
    - Transferring data: transferring_data.md # include Globus
  - Software: software.md
  - Running Jobs: basic_slurm.md
  - Recipes:
    - Snapshots: restoring_data.md
  - Getting Help: getting_help.md
  - Acceptable Use: acceptable_use.md
  - Acknowledging AICR: acknowledging_aicr.md
  - About: about.md #This documentation is created by the teams at [these places], list links to pages we’ve borrowed from
  - Index: tags.md

theme: 
  name: material
#  logo: images/ORCD_logo_icononly.png
  features:
    - content.code.copy
    - content.tabs.link
#  palette:
#    primary: blue grey
plugins:
  - search
  - tags:
      tags_file: tags.md
  - git-revision-date-localized
  - open-in-new-tab
  - table-reader
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.details
  - toc:
      permalink: True
  - attr_list
  - admonition
copyright: <a href="https://accessibility.mit.edu/">Accessibility</a>
